var nama;
var harga;
var jumlah;
var total;
nama = prompt('Nama Barang:'); 
harga = prompt('Harga Satuan:');
jumlah = prompt('Jumlah Beli:');
total = harga * jumlah;
document.writeln('<table border="1">');
document.writeln('<tr>');
document.writeln('<th>Nama Barang</th><th> Harga Satuan</th><th>Jumlah Beli</th><th>Sub Total</th>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + nama + '</td><td>' + harga + '</td><td>' + jumlah + '</td><td>' + total + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td colspan="4">Revand Ronaldy</td>');
document.writeln('</tr>');
document.writeln('</table>');