var a = 11;
var b = 6;
document.writeln("Perkalian : " + a + "*" + b + "=" + (a * b));
document.writeln("<br>");
document.writeln("Pembagian : " + a + "/" + b + "=" + (a / b));
document.writeln("<br>");
document.writeln("Penjumlahan : " + a + "+" + b + "=" + (a + b));
document.writeln("<br>");
document.writeln("Pengurangan : " + a + "-" + b + "=" + (a - b));
document.writeln("<br>");
document.writeln("Modulus : " + a + "%" + b + "=" + (a % b));